name: school_app3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  http_parser: ^4.0.0
  image_picker: ^0.8.4+4
  cached_network_image: ^3.3.0
  intl: ^0.18.0  # Tambahkan baris ini
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Tambahkan baris ini

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Pastikan folder ini ada dan berisi gambar
